### PR TITLE
tal_brain - deleted high threshold and reduced PCs to 6

### PR DESCRIPTION
**Pull request by Taliram**

### CODE REVIEW

**Comment by Taliram** [comment]
Hi,
I just pushed a new commit which includes the brain non-microglia
annotation + astrocyte subcluster analysis.
These graphs should do into the astro figure-
TSNEPlot(object = astro_subtiss, do.label = T)
TSNEPlot(object = astro_subtiss, group.by='subtissue')
DotPlot(astro_subtiss, genes_to_check, plot.legend = T, col.max = 2.5,
do.return = T) + coord_flip()

Please let me know if there is something missing..
Thanks,
Tal

**Comment by Taliram** [comment]
Thanks Olga and sorry for the mess.. 
nick helped me yesterday to resolve some errors I had when I tried to save the notebook as html file. I will update everything on your version and push a new version by tonight.

**Comment by Taliram** [comment]
Hi Olga,
I just pushed your updated version with the new annotations.
Overall I made several changes-
1) with the new clusters there are now 2 neuronal clusters so I added genes
to differentiate between inhibitory and excitatory neurons and was able to
annotate cluster 6 as excitatory and cluster 9 as inhibitory. There are
some neuronal stem cells in cluster 6 (35 cells in total) but I am not sure
if it is possible to have two annotations. I also don't know how to check
the valid annotations for exc/inh neurons so I added it in the free text
for now.

cluster.ids <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
free_annotation = c(NA,NA,NA,NA,NA,NA,"excitatory neurons and some neuronal
stemm cells",NA,
                    NA,"inhibitory neurons")

cell_ontology_class <-
  c(
    "oligodendrocyte",
     "endothelial cell",
    "astrocyte",
     "oligodendrocyte",
     "oligodendrocyte precursor cell",
  "endothelial cell",
   "neuron",
   "oligodendrocyte",
  "brain pericyte",
   "neuron"
  )

2)  I see in the figshare tsne "smooth muscle cells" - I did not annotate
those initially.. I don't know who did and by which genes...

lastly - when I run the subtiss cell ontology part I get this error- and I
can't continue further with the chunks below.. Do you know how to solve it?
Error in lapply(X = X, FUN = FUN, ...) : object 'sub.cell_ontology_class'
not found


Thanks,
Tal

**Comment by nschaum** [comment]
Hey Tal, for that error, check that the object 'sub.cell_ontology_class' is consistently used. For example, you may have something like 'subcell_ontology_class' which is missing the period, giving an error. Just make sure those are all consistent

**Comment by Taliram** [comment]
thanks, it worked!

**Pull request merged**
